name: Publish to JSR
description: ''

inputs:
  deno_version:
    description: ''

runs:
  using: composite
  steps:
    - name: Set up Deno ${{ inputs.deno_version }}
      uses: denoland/setup-deno@v2
      with:
        deno-version: ${{ inputs.deno_version }}

    - name: Publish package
      run: deno publish
      shell: bash
